# Generated by Django 5.2.15 on 2026-06-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_affiliation', models.CharField(choices=[('ABAGUMYABANGA', 'Membre Abagumyabanga (CNDD-FDD)'), ('SYMPATHISANT', 'Sympathisant CNDD-FDD'), ('DIASPORA', 'Diaspora générale / non affilié')], max_length=20, verbose_name="Catégorie d'affiliation")),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('montant_trimestriel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant trimestriel (MAD)')),
            ],
            options={
                'verbose_name': 'Tarif de cotisation',
                'verbose_name_plural': 'Tarifs de cotisation',
                'ordering': ['-annee', 'categorie_affiliation'],
                'unique_together': {('categorie_affiliation', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'T1 (Jan-Mars)'), (2, 'T2 (Avr-Juin)'), (3, 'T3 (Juil-Sep)'), (4, 'T4 (Oct-Déc)')], verbose_name='Trimestre')),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant attendu (MAD)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé (MAD)')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('MOBILE_MONEY', 'Mobile Money'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('A_JOUR', 'À jour'), ('EN_RETARD', 'En retard'), ('PARTIEL', 'Partiel'), ('EXONERE', 'Exonéré')], default='EN_RETARD', max_length=10, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='members.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-annee', '-trimestre', 'membre__nom'],
                'unique_together': {('membre', 'annee', 'trimestre')},
            },
        ),
    ]
