# Generated by Django 5.2.15 on 2026-06-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ville_residence', models.CharField(blank=True, max_length=100, verbose_name='Ville de résidence')),
                ('date_arrivee_maroc', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée au Maroc")),
                ('categorie_affiliation', models.CharField(choices=[('ABAGUMYABANGA', 'Membre Abagumyabanga (CNDD-FDD)'), ('SYMPATHISANT', 'Sympathisant CNDD-FDD'), ('DIASPORA', 'Diaspora générale / non affilié')], default='DIASPORA', max_length=20, verbose_name="Catégorie d'affiliation")),
                ('statut_socio_pro', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('TRAVAILLEUR', 'Travailleur / Professionnel'), ('SANS_ACTIVITE', 'Sans activité déclarée'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Statut socio-professionnel')),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10, verbose_name='Statut du compte')),
                ('date_adhesion', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(max_length=200, verbose_name='Établissement')),
                ('ville_etudes', models.CharField(max_length=100, verbose_name="Ville d'études")),
                ('annee_academique', models.CharField(help_text='Format: 2025-2026', max_length=9, verbose_name='Année académique')),
                ('statut_parcours', models.CharField(choices=[('EN_COURS', 'En cours'), ('DIPLOME', 'Diplômé'), ('ABANDON', 'Abandon'), ('REORIENTATION', 'Réorientation')], default='EN_COURS', max_length=15, verbose_name='Statut du parcours')),
                ('date_diplome', models.DateField(blank=True, null=True, verbose_name='Date de diplôme')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cycle', verbose_name='Cycle')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.domaine', verbose_name='Domaine')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filiere', verbose_name='Filière')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to='members.membre')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Profil étudiant',
                'verbose_name_plural': 'Profils étudiants',
            },
        ),
    ]
