# Generated by Django 5.2.15 on 2026-06-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_add_marrakech_cellule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletudiant',
            name='annee_academique',
            field=models.CharField(blank=True, help_text='Format: 2025-2026', max_length=9, verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='profiletudiant',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='profiletudiant',
            name='ville_etudes',
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville d'études"),
        ),
    ]
